server:
  port: 8005
spring:
  application:
    name: evoc-integrate

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/evoc
    username: root
    password: root



mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.evoc.integrate.domain
  mapper-locations: classpath:mapper/*.xml




